const originalQuestions = [
  { q: "What does CSRF protection prevent in web applications?", opts: ["SQL injection", "Cross-Site Request Forgery", "Cross-Site Scripting", "Denial of Service"], ans: 1 },
  { q: "In Flask, static files are typically stored in which directory?", opts: ["templates/", "static/", "public/", "assets/"], ans: 1 },
  { q: "Django follows which architectural pattern?", opts: ["MVC (Model-View-Controller)", "MVT (Model-View-Template)", "MVVM (Model-View-ViewModel)", "MVP (Model-View-Presenter)"], ans: 1 },
  { q: "In Flask, url_for() function is used to:", opts: ["Create database URLs", "Generate URLs for routes", "Validate URLs", "Parse URLs"], ans: 1 },
  { q: "Which of the following is a characteristic of Flask?", opts: ["Built-in admin interface", "Built-in ORM", "Minimalistic and flexible", "Requires specific project structure"], ans: 2 },
  { q: "In Django, models are defined in which file?", opts: ["models.py", "views.py", "urls.py", "settings.py"], ans: 0 },
  { q: "What does ORM stand for?", opts: ["Object-Relational Mapping", "Object-Relational Model", "Object-Resource Mapping", "Operation-Resource Management"], ans: 0 },
  { q: "In SQLAlchemy, what does the Session object manage?", opts: ["Database connections only", "Transactions and object persistence", "Only query building", "Only schema creation"], ans: 1 },
  { q: "Which of the following is NOT an ORM framework for Python?", opts: ["SQLAlchemy", "Django ORM", "Hibernate", "Peewee"], ans: 2 },
  { q: "In SQLAlchemy, what does declarative_base() create?", opts: ["A database connection", "A base class for ORM models", "A session factory", "An engine"], ans: 1 },
  { q: "What is the purpose of session.commit() in SQLAlchemy?", opts: ["Rolls back changes", "Saves changes to the database", "Closes the session", "Creates a new session"], ans: 1 },
  { q: "In Django ORM, objects.all() returns:", opts: ["A single object", "All objects in the database table", "The first object", "The last object"], ans: 1 },
  { q: "Which method is used to filter results in Django ORM?", opts: ["filter()", "where()", "select()", "find()"], ans: 0 },
  { q: "In SQLAlchemy, session.query(User).filter_by(name='John').first() returns:", opts: ["All users named John", "The first user named John", "A list of users named John", "None of the above"], ans: 1 },
  { q: "What is the primary advantage of using ORM?", opts: ["Faster than raw SQL", "Python code instead of SQL", "No need for databases", "Automatic indexing"], ans: 1 },
  { q: "In Django, which method is used to save a model instance to the database?", opts: ["save()", "insert()", "create()", "store()"], ans: 0 },
  { q: "SQLAlchemy's create_engine() function:", opts: ["Creates a database", "Creates a database engine/connection pool", "Creates tables", "Creates ORM models"], ans: 1 },
  { q: "Which of the following is NOT a CRUD operation?", opts: ["Create", "Read", "Update", "Compile"], ans: 3 },
  { q: "In Django ORM, what does get(id=1) do?", opts: ["Returns all objects", "Returns the object with id=1 or raises DoesNotExist", "Returns None if not found", "Returns a list of objects"], ans: 1 },
  { q: "In SQLAlchemy, a flush operation:", opts: ["Closes the database connection", "Synchronizes session state with the database", "Deletes all data", "Creates tables"], ans: 1 },
  { q: "What is the Unit of Work pattern?", opts: ["A pattern for database migration", "A pattern for maintaining a list of objects affected by a transaction", "A pattern for database indexing", "A pattern for caching"], ans: 1 },
  { q: "In Django, __str__ method in a model is used for:", opts: ["Database indexing", "Human-readable representation of the object", "String formatting of queries", "Field validation"], ans: 1 },
  { q: "Which of the following is a database security best practice?", opts: ["Storing passwords in plain text", "Using parameterized queries", "Using root user for all operations", "Disabling SSL"], ans: 1 },
  { q: "In Django ORM, objects.create():", opts: ["Creates a new object and saves it", "Only creates the object without saving", "Creates a database table", "Creates a migration"], ans: 0 },
  { q: "SQLAlchemy supports which databases?", opts: ["Only SQLite", "Only PostgreSQL", "Multiple databases including SQLite, PostgreSQL, MySQL", "Only MySQL"], ans: 2 },
  { q: "In Django, what does python manage.py makemigrations do?", opts: ["Applies migrations to the database", "Creates new migration files based on model changes", "Rolls back migrations", "Deletes the database"], ans: 1 },
  { q: "Which of the following helps prevent SQL injection?", opts: ["String concatenation for queries", "Parameterized queries", "Storing queries in files", "Using eval()"], ans: 1 },
  { q: "In SQLAlchemy, what is a sessionmaker?", opts: ["A class that creates Session objects", "A class that creates Engine objects", "A class that creates Base objects", "A class that creates tables"], ans: 0 },
  { q: "In Django, ForeignKey is used to define:", opts: ["A one-to-many relationship", "A many-to-many relationship", "A one-to-one relationship", "A primary key"], ans: 0 },
  { q: "What is the purpose of database transactions?", opts: ["To speed up queries", "To ensure data consistency and integrity", "To delete data", "To create tables"], ans: 1 },
  { q: "In SQLAlchemy, which method deletes an object from the database?", opts: ["session.delete(object)", "session.remove(object)", "session.drop(object)", "session.erase(object)"], ans: 0 },
  { q: "What does GIL stand for in Python?", opts: ["Global Interface Lock", "Global Interpreter Lock", "General Input Language", "Generic Iteration Loop"], ans: 1 },
  { q: "The GIL prevents:", opts: ["Multiple processes from running", "Multiple threads from executing Python bytecode simultaneously", "Multiple CPUs from being used", "I/O operations"], ans: 1 },
  { q: "Which Python module is used for creating threads?", opts: ["threading", "thread", "multiprocessing", "asyncio"], ans: 0 },
  { q: "Which approach is best for CPU-bound tasks in Python?", opts: ["Threading", "Multiprocessing", "asyncio", "Single-threaded"], ans: 1 },
  { q: "Which module is used for asynchronous programming in Python?", opts: ["threading", "multiprocessing", "asyncio", "concurrent"], ans: 2 },
  { q: "What is a coroutine in Python?", opts: ["A function defined with def", "A function defined with async def", "A function defined with coroutine def", "A class"], ans: 1 },
  { q: "Which keyword is used to wait for an awaitable object in Python?", opts: ["wait", "yield", "await", "pause"], ans: 2 },
  { q: "Asyncio is best suited for:", opts: ["CPU-bound tasks", "I/O-bound tasks with high concurrency", "Memory-bound tasks", "Disk-bound tasks only"], ans: 1 },
  { q: "In multiprocessing, each process has:", opts: ["Shared memory with other processes", "Its own Python interpreter and memory space", "The same global variables", "No memory"], ans: 1 },
  { q: "Which method is used to start a thread in Python?", opts: ["thread.start()", "thread.run()", "thread.begin()", "thread.execute()"], ans: 0 },
  { q: "What does thread.join() do?", opts: ["Terminates the thread", "Waits for the thread to finish", "Starts the thread", "Pauses the thread"], ans: 1 },
  { q: "In asyncio, what is an event loop?", opts: ["A loop for iterating over events", "The core scheduler that runs coroutines", "A database connection pool", "A threading pool"], ans: 1 },
  { q: "Which of the following is true about threading in Python?", opts: ["Threads can run in parallel on multiple CPUs", "Threads are limited by the GIL for CPU-bound tasks", "Threads cannot perform I/O operations", "Threads cannot share data"], ans: 1 },
  { q: "asyncio.gather() is used to:", opts: ["Execute coroutines sequentially", "Execute multiple coroutines concurrently", "Create new coroutines", "Stop the event loop"], ans: 1 },
  { q: "Which of the following is a synchronization primitive in threading?", opts: ["Lock", "Queue", "List", "Dictionary"], ans: 0 },
  { q: "The multiprocessing module provides:", opts: ["Only thread-based parallelism", "Process-based parallelism", "Only asynchronous programming", "Only single-threaded execution"], ans: 1 },
  { q: "What is the difference between concurrency and parallelism?", opts: ["They are the same thing", "Concurrency is about dealing with multiple tasks; parallelism is about executing multiple tasks simultaneously", "Parallelism is about dealing with multiple tasks; concurrency is about executing multiple tasks simultaneously", "Neither involves multiple tasks"], ans: 1 },
  { q: "In asyncio, asyncio.run():", opts: ["Runs a coroutine and manages the event loop", "Runs multiple threads", "Runs a process", "Runs a database query"], ans: 0 },
  { q: "Which of the following is NOT a concurrency approach in Python?", opts: ["Threading", "Multiprocessing", "Asyncio", "Multiprocessing.distributed"], ans: 3 },
  { q: "What is the main limitation of asyncio?", opts: ["It cannot handle I/O operations", "It requires libraries that support async operations", "It is slower than threading", "It cannot run on Windows"], ans: 1 },
  { q: "In threading, what is a race condition?", opts: ["Two threads running at the same speed", "When multiple threads access shared data and the result depends on execution order", "When a thread stops unexpectedly", "When a thread cannot start"], ans: 1 },
  { q: "Which module provides a thread-safe queue?", opts: ["queue", "collections", "list", "set"], ans: 0 },
  { q: "Asyncio uses which programming model?", opts: ["Multi-threaded", "Multi-process", "Single-threaded concurrent", "Distributed"], ans: 2 },
  { q: "Which of the following is an I/O-bound task?", opts: ["Matrix multiplication", "Sorting a large array", "Reading a file from disk", "Calculating prime numbers"], ans: 2 },
  { q: "In multiprocessing, Pool.map() is used for:", opts: ["Mapping data to threads", "Applying a function to each element in parallel", "Mapping processes to CPUs", "Mapping database queries"], ans: 1 },
  { q: "NumPy's primary data structure is called:", opts: ["array", "ndarray", "list", "dataframe"], ans: 1 },
  { q: "What is the output of np.array([1,2,3]) + np.array([4,5,6])?", opts: ["[5,7,9]", "[1,2,3,4,5,6]", "Error", "[4,10,18]"], ans: 0 },
  { q: "Which function creates an array of zeros?", opts: ["np.zero()", "np.zeros()", "np.zeros_array()", "np.array(0)"], ans: 1 },
  { q: "np.arange(5) returns:", opts: ["[0,1,2,3,4]", "[1,2,3,4,5]", "[0,1,2,3,4,5]", "[5,4,3,2,1]"], ans: 0 },
  { q: "What does np.mean(arr) compute?", opts: ["Median", "Average", "Mode", "Variance"], ans: 1 },
  { q: "Which method reshapes a NumPy array?", opts: ["reshape()", "resize()", "shape()", "reform()"], ans: 0 },
  { q: "NumPy arrays are:", opts: ["Slower than Python lists", "Faster than Python lists for numerical operations", "The same speed as Python lists", "Slower for all operations"], ans: 1 },
  { q: "What is broadcasting in NumPy?", opts: ["Sending data to multiple processes", "Performing operations on arrays of different shapes", "Creating arrays from lists", "Visualizing data"], ans: 1 },
  { q: "np.linspace(0, 10, 5) returns:", opts: ["[0, 2, 4, 6, 8, 10]", "[0, 2.5, 5, 7.5, 10]", "[0, 10, 20, 30, 40]", "Error"], ans: 1 },
  { q: "Which function computes the standard deviation?", opts: ["np.std()", "np.mean()", "np.var()", "np.median()"], ans: 0 },
  { q: "What is the shape of np.zeros((3,4))?", opts: ["(3,)", "(4,)", "(3,4)", "(4,3)"], ans: 2 },
  { q: "NumPy is built on which language?", opts: ["Java", "C", "Ruby", "JavaScript"], ans: 1 },
  { q: "Which operation performs element-wise multiplication in NumPy?", opts: ["np.dot(a,b)", "a * b", "a @ b", "np.matmul(a,b)"], ans: 1 },
  { q: "np.random.randn(10) generates:", opts: ["10 random integers", "10 random numbers from standard normal distribution", "10 random numbers from uniform distribution", "10 zeros"], ans: 1 },
  { q: "How do you check the shape of a NumPy array?", opts: ["arr.shape()", "arr.shape", "arr.size", "arr.dim"], ans: 1 },
  { q: "Pandas is built on top of which library?", opts: ["Matplotlib", "NumPy", "SciPy", "Scikit-learn"], ans: 1 },
  { q: "The two primary data structures in Pandas are:", opts: ["List and Tuple", "Series and DataFrame", "Array and Matrix", "Dict and Set"], ans: 1 },
  { q: "A Pandas Series is:", opts: ["Two-dimensional labeled data", "One-dimensional labeled array", "Three-dimensional data", "Unlabeled data"], ans: 1 },
  { q: "How do you read a CSV file in Pandas?", opts: ["pd.read_csv()", "pd.load_csv()", "pd.import_csv()", "pd.csv_read()"], ans: 0 },
  { q: "df.head() displays:", opts: ["First 5 rows by default", "Last 5 rows", "All rows", "First 10 rows"], ans: 0 },
  { q: "Which method shows summary statistics of a DataFrame?", opts: ["df.summary()", "df.describe()", "df.stats()", "df.info()"], ans: 1 },
  { q: "How do you select a single column in Pandas?", opts: ["df['column_name']", "df.column_name", "Both A and B", "df.select('column_name')"], ans: 2 },
  { q: "Which method removes rows with missing values?", opts: ["df.dropna()", "df.fillna()", "df.remove_na()", "df.clean()"], ans: 0 },
  { q: "How do you group data in Pandas?", opts: ["df.groupby()", "df.group()", "df.aggregate()", "df.partition()"], ans: 0 },
  { q: "Which method fills missing values?", opts: ["df.dropna()", "df.fillna()", "df.replace()", "df.update()"], ans: 1 },
  { q: "Pandas DataFrame is:", opts: ["One-dimensional", "Two-dimensional labeled data", "Three-dimensional", "Unlabeled"], ans: 1 },
  { q: "Which method merges two DataFrames?", opts: ["df.merge()", "df.join()", "df.concat()", "All of the above"], ans: 3 },
  { q: "How do you check for null values in a DataFrame?", opts: ["df.isnull()", "df.null()", "df.isna()", "Both A and C"], ans: 3 },
  { q: "df['column'].value_counts() returns:", opts: ["Sum of values", "Count of unique values", "Mean of values", "Median of values"], ans: 1 },
  { q: "Pandas is commonly used for:", opts: ["Web development", "Data manipulation and analysis", "Game development", "Operating systems"], ans: 1 },
  { q: "Matplotlib is primarily used for:", opts: ["Data visualization", "Data manipulation", "Machine learning", "Web development"], ans: 0 },
  { q: "Which function creates a plot in Matplotlib?", opts: ["plt.plot()", "plt.draw()", "plt.show()", "plt.create()"], ans: 0 },
  { q: "How do you display a plot in Matplotlib?", opts: ["plt.display()", "plt.show()", "plt.render()", "plt.view()"], ans: 1 },
  { q: "Which function creates a scatter plot?", opts: ["plt.scatter()", "plt.plot()", "plt.bar()", "plt.hist()"], ans: 0 },
  { q: "How do you add a title to a plot?", opts: ["plt.title()", "plt.label()", "plt.heading()", "plt.text()"], ans: 0 },
  { q: "Which function creates a histogram?", opts: ["plt.hist()", "plt.bar()", "plt.plot()", "plt.scatter()"], ans: 0 },
  { q: "How do you add a legend to a plot?", opts: ["plt.legend()", "plt.label()", "plt.key()", "plt.notes()"], ans: 0 },
  { q: "Which function creates subplots?", opts: ["plt.subplots()", "plt.subplot()", "Both A and B", "plt.figures()"], ans: 2 },
  { q: "Matplotlib can save figures using:", opts: ["plt.save()", "plt.savefig()", "plt.export()", "plt.write()"], ans: 1 },
  { q: "Which of the following is NOT a plot type in Matplotlib?", opts: ["Line plot", "Bar chart", "Pie chart", "Network graph (default)"], ans: 3 },
  { q: "Scikit-learn is a library for:", opts: ["Web development", "Machine learning", "Data visualization", "Database management"], ans: 1 },
  { q: "Which of the following is a supervised learning task?", opts: ["Clustering", "Classification", "Dimensionality reduction", "Association rule learning"], ans: 1 },
  { q: "Which algorithm is used for clustering?", opts: ["Linear Regression", "k-Means", "Decision Tree", "SVM"], ans: 1 },
  { q: "In train_test_split(), what does the test_size parameter specify?", opts: ["Number of training samples", "Proportion of data for testing", "Number of test samples", "Size of the dataset"], ans: 1 }
];


